// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Org.OData.Capabilities.V1.ConformanceLevelType
    /// </summary>
    public enum ConformanceLevelType
    {
        /// <summary>
        /// Minimal conformance level
        /// </summary>
        Minimal,

        /// <summary>
        /// Intermediate conformance level
        /// </summary>
        Intermediate,

        /// <summary>
        /// Advanced conformance level
        /// </summary>
        Advanced,
    }
}
