// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Restrictions on expand expressions
    /// </summary>
    public partial class ExpandRestrictionsConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _expandable;
        private bool? _streamsExpandable;
        private readonly HashSet<EdmNavigationPropertyPathExpression> _nonExpandableProperties = new HashSet<EdmNavigationPropertyPathExpression>();
        private readonly HashSet<EdmPropertyPathExpression> _nonExpandableStreamProperties = new HashSet<EdmPropertyPathExpression>();
        private int? _maxLevels;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Capabilities.V1.ExpandRestrictions";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// $expand is supported
        /// </summary>
        /// <param name="expandable">The value to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration IsExpandable(bool expandable)
        {
            _expandable = expandable;
            return this;
        }

        /// <summary>
        /// $expand is supported for stream properties and media streams
        /// </summary>
        /// <param name="streamsExpandable">The value to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration IsStreamsExpandable(bool streamsExpandable)
        {
            _streamsExpandable = streamsExpandable;
            return this;
        }

        /// <summary>
        /// These properties cannot be used in expand expressions
        /// </summary>
        /// <param name="nonExpandableProperties">The value(s) to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration HasNonExpandableProperties(params EdmNavigationPropertyPathExpression[] nonExpandableProperties)
        {
            _nonExpandableProperties.UnionWith(nonExpandableProperties);
            return this;
        }

        /// <summary>
        /// These stream properties cannot be used in expand expressions
        /// </summary>
        /// <param name="nonExpandableStreamProperties">The value(s) to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration HasNonExpandableStreamProperties(params EdmPropertyPathExpression[] nonExpandableStreamProperties)
        {
            _nonExpandableStreamProperties.UnionWith(nonExpandableStreamProperties);
            return this;
        }

        /// <summary>
        /// The maximum number of levels that can be expanded in a expand expression. A value of -1 indicates there is no restriction.
        /// </summary>
        /// <param name="maxLevels">The value to set</param>
        /// <returns><see cref="ExpandRestrictionsConfiguration"/></returns>
        public ExpandRestrictionsConfiguration HasMaxLevels(int maxLevels)
        {
            _maxLevels = maxLevels;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_expandable.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("Expandable", new EdmBooleanConstant(_expandable.Value)));
            }

            if (_streamsExpandable.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("StreamsExpandable", new EdmBooleanConstant(_streamsExpandable.Value)));
            }

            if (_nonExpandableProperties.Any())
            {
                var collection = _nonExpandableProperties.Where(item => item != null);
                if (collection.Any())
                {
                    properties.Add(new EdmPropertyConstructor("NonExpandableProperties", new EdmCollectionExpression(collection)));
                }
            }

            if (_nonExpandableStreamProperties.Any())
            {
                var collection = _nonExpandableStreamProperties.Where(item => item != null);
                if (collection.Any())
                {
                    properties.Add(new EdmPropertyConstructor("NonExpandableStreamProperties", new EdmCollectionExpression(collection)));
                }
            }

            if (_maxLevels.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("MaxLevels", new EdmIntegerConstant(_maxLevels.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
