// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Supported odata.isolation levels
    /// </summary>
    public partial class IsolationSupportedConfiguration : VocabularyTermConfiguration
    {
        private IsolationLevel? _isolationSupported;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Capabilities.V1.IsolationSupported";

        /// <summary>
        /// Supported odata.isolation levels
        /// </summary>
        /// <param name="isolationSupported">The value to set</param>
        /// <returns><see cref="IsolationSupportedConfiguration"/></returns>
        public IsolationSupportedConfiguration HasIsolationSupported(IsolationLevel isolationSupported)
        {
            _isolationSupported = isolationSupported;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_isolationSupported.HasValue)
            {
                var enumType = new EdmEnumType("Org.OData.Capabilities.V1", "IsolationLevel", true);
                var enumMember = new EdmEnumMember(enumType, _isolationSupported.ToString(), new EdmEnumMemberValue((long)_isolationSupported.Value));
                properties.Add(new EdmPropertyConstructor("IsolationSupported", new EdmEnumMemberExpression(enumMember)));
            }

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
