// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Supports [key-as-segment convention](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_KeyasSegmentConvention) for addressing entities within a collection
    /// </summary>
    public partial class KeyAsSegmentSupportedConfiguration : VocabularyTermConfiguration
    {
        private bool? _keyAsSegmentSupported;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Capabilities.V1.KeyAsSegmentSupported";

        /// <summary>
        /// Supports [key-as-segment convention](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_KeyasSegmentConvention) for addressing entities within a collection
        /// </summary>
        /// <param name="keyAsSegmentSupported">The value to set</param>
        /// <returns><see cref="KeyAsSegmentSupportedConfiguration"/></returns>
        public KeyAsSegmentSupportedConfiguration IsKeyAsSegmentSupported(bool keyAsSegmentSupported)
        {
            _keyAsSegmentSupported = keyAsSegmentSupported;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return _keyAsSegmentSupported.HasValue ? new EdmBooleanConstant(_keyAsSegmentSupported) : null;
        }
    }
}
