// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Using a property of `NavigationPropertyRestriction` in a [`NavigationRestrictions`](#NavigationRestrictions) annotation
    ///           is discouraged in favor of using an annotation with the corresponding term from this vocabulary and a target path starting with a container and ending in the `NavigationProperty`,
    ///           unless the favored alternative is impossible because a dynamic expression requires an instance path whose evaluation
    ///           starts at the target of the `NavigationRestrictions` annotation. See [this example](../examples/Org.OData.Capabilities.V1.capabilities.md).
    /// </summary>
    public partial class NavigationPropertyRestrictionConfiguration : IRecord
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private EdmNavigationPropertyPathExpression _navigationProperty;
        private NavigationType? _navigability;
        private readonly HashSet<string> _filterFunctions = new HashSet<string>();
        private FilterRestrictionsConfiguration _filterRestrictions;
        private SearchRestrictionsConfiguration _searchRestrictions;
        private SortRestrictionsConfiguration _sortRestrictions;
        private bool? _topSupported;
        private bool? _skipSupported;
        private SelectSupportConfiguration _selectSupport;
        private bool? _indexableByKey;
        private InsertRestrictionsConfiguration _insertRestrictions;
        private DeepInsertSupportConfiguration _deepInsertSupport;
        private UpdateRestrictionsConfiguration _updateRestrictions;
        private DeepUpdateSupportConfiguration _deepUpdateSupport;
        private DeleteRestrictionsConfiguration _deleteRestrictions;
        private bool? _optimisticConcurrencyControl;
        private ReadRestrictionsConfiguration _readRestrictions;

        /// <summary>
        /// Creates a new instance of <see cref="NavigationPropertyRestrictionConfiguration"/>
        /// </summary>
        public NavigationPropertyRestrictionConfiguration()
        {
        }

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Navigation properties can be navigated
        /// The target path of a [`NavigationRestrictions`](#NavigationRestrictions) annotation followed by this
        ///             navigation property path addresses the resource to which the other properties of `NavigationPropertyRestriction` apply.
        ///             Instance paths that occur in dynamic expressions are evaluated starting at the boundary between both paths,
        ///             which must therefore be chosen accordingly.
        /// </summary>
        /// <param name="navigationProperty">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasNavigationProperty(EdmNavigationPropertyPathExpression navigationProperty)
        {
            _navigationProperty = navigationProperty;
            return this;
        }

        /// <summary>
        /// Supported navigability of this navigation property
        /// </summary>
        /// <param name="navigability">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasNavigability(NavigationType navigability)
        {
            _navigability = navigability;
            return this;
        }

        /// <summary>
        /// List of functions and operators supported in filter expressions
        /// If not specified, null, or empty, all functions and operators may be attempted.
        /// </summary>
        /// <param name="filterFunctions">The value(s) to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasFilterFunctions(params string[] filterFunctions)
        {
            _filterFunctions.UnionWith(filterFunctions);
            return this;
        }

        /// <summary>
        /// Restrictions on filter expressions
        /// </summary>
        /// <param name="filterRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasFilterRestrictions(Func<FilterRestrictionsConfiguration, FilterRestrictionsConfiguration> filterRestrictionsConfiguration)
        {
            var instance = _filterRestrictions ?? new FilterRestrictionsConfiguration();
            instance = filterRestrictionsConfiguration?.Invoke(instance);
            return HasFilterRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on filter expressions
        /// </summary>
        /// <param name="filterRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasFilterRestrictions(FilterRestrictionsConfiguration filterRestrictions)
        {
            _filterRestrictions = filterRestrictions;
            return this;
        }

        /// <summary>
        /// Restrictions on search expressions
        /// </summary>
        /// <param name="searchRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSearchRestrictions(Func<SearchRestrictionsConfiguration, SearchRestrictionsConfiguration> searchRestrictionsConfiguration)
        {
            var instance = _searchRestrictions ?? new SearchRestrictionsConfiguration();
            instance = searchRestrictionsConfiguration?.Invoke(instance);
            return HasSearchRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on search expressions
        /// </summary>
        /// <param name="searchRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSearchRestrictions(SearchRestrictionsConfiguration searchRestrictions)
        {
            _searchRestrictions = searchRestrictions;
            return this;
        }

        /// <summary>
        /// Restrictions on orderby expressions
        /// </summary>
        /// <param name="sortRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSortRestrictions(Func<SortRestrictionsConfiguration, SortRestrictionsConfiguration> sortRestrictionsConfiguration)
        {
            var instance = _sortRestrictions ?? new SortRestrictionsConfiguration();
            instance = sortRestrictionsConfiguration?.Invoke(instance);
            return HasSortRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on orderby expressions
        /// </summary>
        /// <param name="sortRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSortRestrictions(SortRestrictionsConfiguration sortRestrictions)
        {
            _sortRestrictions = sortRestrictions;
            return this;
        }

        /// <summary>
        /// Supports $top
        /// </summary>
        /// <param name="topSupported">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration IsTopSupported(bool topSupported)
        {
            _topSupported = topSupported;
            return this;
        }

        /// <summary>
        /// Supports $skip
        /// </summary>
        /// <param name="skipSupported">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration IsSkipSupported(bool skipSupported)
        {
            _skipSupported = skipSupported;
            return this;
        }

        /// <summary>
        /// Support for $select
        /// </summary>
        /// <param name="selectSupportConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSelectSupport(Func<SelectSupportConfiguration, SelectSupportConfiguration> selectSupportConfiguration)
        {
            var instance = _selectSupport ?? new SelectSupportConfiguration();
            instance = selectSupportConfiguration?.Invoke(instance);
            return HasSelectSupport(instance);
        }

        /// <summary>
        /// Support for $select
        /// </summary>
        /// <param name="selectSupport">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasSelectSupport(SelectSupportConfiguration selectSupport)
        {
            _selectSupport = selectSupport;
            return this;
        }

        /// <summary>
        /// Supports key values according to OData URL conventions
        /// </summary>
        /// <param name="indexableByKey">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration IsIndexableByKey(bool indexableByKey)
        {
            _indexableByKey = indexableByKey;
            return this;
        }

        /// <summary>
        /// Restrictions on insert operations
        /// </summary>
        /// <param name="insertRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasInsertRestrictions(Func<InsertRestrictionsConfiguration, InsertRestrictionsConfiguration> insertRestrictionsConfiguration)
        {
            var instance = _insertRestrictions ?? new InsertRestrictionsConfiguration();
            instance = insertRestrictionsConfiguration?.Invoke(instance);
            return HasInsertRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on insert operations
        /// </summary>
        /// <param name="insertRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasInsertRestrictions(InsertRestrictionsConfiguration insertRestrictions)
        {
            _insertRestrictions = insertRestrictions;
            return this;
        }

        /// <summary>
        /// Deep Insert Support of the annotated resource (the whole service, an entity set, or a collection-valued resource)
        /// </summary>
        /// <param name="deepInsertSupportConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeepInsertSupport(Func<DeepInsertSupportConfiguration, DeepInsertSupportConfiguration> deepInsertSupportConfiguration)
        {
            var instance = _deepInsertSupport ?? new DeepInsertSupportConfiguration();
            instance = deepInsertSupportConfiguration?.Invoke(instance);
            return HasDeepInsertSupport(instance);
        }

        /// <summary>
        /// Deep Insert Support of the annotated resource (the whole service, an entity set, or a collection-valued resource)
        /// </summary>
        /// <param name="deepInsertSupport">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeepInsertSupport(DeepInsertSupportConfiguration deepInsertSupport)
        {
            _deepInsertSupport = deepInsertSupport;
            return this;
        }

        /// <summary>
        /// Restrictions on update operations
        /// </summary>
        /// <param name="updateRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasUpdateRestrictions(Func<UpdateRestrictionsConfiguration, UpdateRestrictionsConfiguration> updateRestrictionsConfiguration)
        {
            var instance = _updateRestrictions ?? new UpdateRestrictionsConfiguration();
            instance = updateRestrictionsConfiguration?.Invoke(instance);
            return HasUpdateRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on update operations
        /// </summary>
        /// <param name="updateRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasUpdateRestrictions(UpdateRestrictionsConfiguration updateRestrictions)
        {
            _updateRestrictions = updateRestrictions;
            return this;
        }

        /// <summary>
        /// Deep Update Support of the annotated resource (the whole service, an entity set, or a collection-valued resource)
        /// </summary>
        /// <param name="deepUpdateSupportConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeepUpdateSupport(Func<DeepUpdateSupportConfiguration, DeepUpdateSupportConfiguration> deepUpdateSupportConfiguration)
        {
            var instance = _deepUpdateSupport ?? new DeepUpdateSupportConfiguration();
            instance = deepUpdateSupportConfiguration?.Invoke(instance);
            return HasDeepUpdateSupport(instance);
        }

        /// <summary>
        /// Deep Update Support of the annotated resource (the whole service, an entity set, or a collection-valued resource)
        /// </summary>
        /// <param name="deepUpdateSupport">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeepUpdateSupport(DeepUpdateSupportConfiguration deepUpdateSupport)
        {
            _deepUpdateSupport = deepUpdateSupport;
            return this;
        }

        /// <summary>
        /// Restrictions on delete operations
        /// </summary>
        /// <param name="deleteRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeleteRestrictions(Func<DeleteRestrictionsConfiguration, DeleteRestrictionsConfiguration> deleteRestrictionsConfiguration)
        {
            var instance = _deleteRestrictions ?? new DeleteRestrictionsConfiguration();
            instance = deleteRestrictionsConfiguration?.Invoke(instance);
            return HasDeleteRestrictions(instance);
        }

        /// <summary>
        /// Restrictions on delete operations
        /// </summary>
        /// <param name="deleteRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasDeleteRestrictions(DeleteRestrictionsConfiguration deleteRestrictions)
        {
            _deleteRestrictions = deleteRestrictions;
            return this;
        }

        /// <summary>
        /// Data modification (including insert) along this navigation property requires the use of ETags
        /// </summary>
        /// <param name="optimisticConcurrencyControl">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration IsOptimisticConcurrencyControl(bool optimisticConcurrencyControl)
        {
            _optimisticConcurrencyControl = optimisticConcurrencyControl;
            return this;
        }

        /// <summary>
        /// Restrictions for retrieving entities
        /// </summary>
        /// <param name="readRestrictionsConfiguration">The configuration to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasReadRestrictions(Func<ReadRestrictionsConfiguration, ReadRestrictionsConfiguration> readRestrictionsConfiguration)
        {
            var instance = _readRestrictions ?? new ReadRestrictionsConfiguration();
            instance = readRestrictionsConfiguration?.Invoke(instance);
            return HasReadRestrictions(instance);
        }

        /// <summary>
        /// Restrictions for retrieving entities
        /// </summary>
        /// <param name="readRestrictions">The value to set</param>
        /// <returns><see cref="NavigationPropertyRestrictionConfiguration"/></returns>
        public NavigationPropertyRestrictionConfiguration HasReadRestrictions(ReadRestrictionsConfiguration readRestrictions)
        {
            _readRestrictions = readRestrictions;
            return this;
        }

        /// <inheritdoc/>
        public IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_navigationProperty != null)
            {
                properties.Add(new EdmPropertyConstructor("NavigationProperty", _navigationProperty));
            }

            if (_navigability.HasValue)
            {
                var enumType = new EdmEnumType("Org.OData.Capabilities.V1", "NavigationType", false);
                var enumMember = new EdmEnumMember(enumType, _navigability.ToString(), new EdmEnumMemberValue((long)_navigability.Value));
                properties.Add(new EdmPropertyConstructor("Navigability", new EdmEnumMemberExpression(enumMember)));
            }

            if (_filterFunctions.Any())
            {
                var collection = _filterFunctions.Select(item => item.ToEdmExpression()).Where(item => item != null);
                if (collection.Any())
                {
                    properties.Add(new EdmPropertyConstructor("FilterFunctions", new EdmCollectionExpression(collection)));
                }
            }

            if (_filterRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("FilterRestrictions", _filterRestrictions.ToEdmExpression()));
            }

            if (_searchRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("SearchRestrictions", _searchRestrictions.ToEdmExpression()));
            }

            if (_sortRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("SortRestrictions", _sortRestrictions.ToEdmExpression()));
            }

            if (_topSupported.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("TopSupported", new EdmBooleanConstant(_topSupported.Value)));
            }

            if (_skipSupported.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("SkipSupported", new EdmBooleanConstant(_skipSupported.Value)));
            }

            if (_selectSupport != null)
            {
                properties.Add(new EdmPropertyConstructor("SelectSupport", _selectSupport.ToEdmExpression()));
            }

            if (_indexableByKey.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("IndexableByKey", new EdmBooleanConstant(_indexableByKey.Value)));
            }

            if (_insertRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("InsertRestrictions", _insertRestrictions.ToEdmExpression()));
            }

            if (_deepInsertSupport != null)
            {
                properties.Add(new EdmPropertyConstructor("DeepInsertSupport", _deepInsertSupport.ToEdmExpression()));
            }

            if (_updateRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("UpdateRestrictions", _updateRestrictions.ToEdmExpression()));
            }

            if (_deepUpdateSupport != null)
            {
                properties.Add(new EdmPropertyConstructor("DeepUpdateSupport", _deepUpdateSupport.ToEdmExpression()));
            }

            if (_deleteRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("DeleteRestrictions", _deleteRestrictions.ToEdmExpression()));
            }

            if (_optimisticConcurrencyControl.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("OptimisticConcurrencyControl", new EdmBooleanConstant(_optimisticConcurrencyControl.Value)));
            }

            if (_readRestrictions != null)
            {
                properties.Add(new EdmPropertyConstructor("ReadRestrictions", _readRestrictions.ToEdmExpression()));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
