// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Capabilities.V1
{
    /// <summary>
    /// Media types of supported formats, including format parameters
    /// </summary>
    public partial class SupportedFormatsConfiguration : VocabularyTermConfiguration
    {
        private readonly HashSet<string> _supportedFormats = new HashSet<string>();

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Capabilities.V1.SupportedFormats";

        /// <summary>
        /// Media types of supported formats, including format parameters
        /// </summary>
        /// <param name="supportedFormats">The value(s) to set</param>
        /// <returns><see cref="SupportedFormatsConfiguration"/></returns>
        public SupportedFormatsConfiguration HasSupportedFormats(params string[] supportedFormats)
        {
            _supportedFormats.UnionWith(supportedFormats);
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            if (!_supportedFormats.Any())
            {
                return null;
            }

            var records = _supportedFormats.Select(item => item.ToEdmExpression());
            return new EdmCollectionExpression(records);
        }
    }
}
