// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Lists the MIME types acceptable for the annotated entity type marked with HasStream="true" or the annotated binary, stream, or string property or term
    /// The annotation of a TypeDefinition propagates to the model elements having this type
    /// </summary>
    public partial class AcceptableMediaTypesConfiguration : VocabularyTermConfiguration
    {
        private readonly HashSet<string> _acceptableMediaTypes = new HashSet<string>();

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.AcceptableMediaTypes";

        /// <summary>
        /// Lists the MIME types acceptable for the annotated entity type marked with HasStream="true" or the annotated binary, stream, or string property or term
        /// The annotation of a TypeDefinition propagates to the model elements having this type
        /// </summary>
        /// <param name="acceptableMediaTypes">The value(s) to set</param>
        /// <returns><see cref="AcceptableMediaTypesConfiguration"/></returns>
        public AcceptableMediaTypesConfiguration HasAcceptableMediaTypes(params string[] acceptableMediaTypes)
        {
            _acceptableMediaTypes.UnionWith(acceptableMediaTypes);
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            if (!_acceptableMediaTypes.Any())
            {
                return null;
            }

            var records = _acceptableMediaTypes.Select(item => item.ToEdmExpression());
            return new EdmCollectionExpression(records);
        }
    }
}
