// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// The service will automatically expand this navigation property as entity references even if not requested with $expand=.../$ref
    /// </summary>
    public partial class AutoExpandReferencesConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _autoExpandReferences;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.AutoExpandReferences";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="AutoExpandReferencesConfiguration"/></returns>
        public AutoExpandReferencesConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// The service will automatically expand this navigation property as entity references even if not requested with $expand=.../$ref
        /// </summary>
        /// <param name="autoExpandReferences">The value to set</param>
        /// <returns><see cref="AutoExpandReferencesConfiguration"/></returns>
        public AutoExpandReferencesConfiguration IsAutoExpandReferences(bool autoExpandReferences)
        {
            _autoExpandReferences = autoExpandReferences;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_autoExpandReferences.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("AutoExpandReferences", new EdmBooleanConstant(_autoExpandReferences.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
