// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// The service will automatically expand this stream or navigation property even if not requested with $expand
    /// </summary>
    public partial class AutoExpandConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _autoExpand;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.AutoExpand";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="AutoExpandConfiguration"/></returns>
        public AutoExpandConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// The service will automatically expand this stream or navigation property even if not requested with $expand
        /// </summary>
        /// <param name="autoExpand">The value to set</param>
        /// <returns><see cref="AutoExpandConfiguration"/></returns>
        public AutoExpandConfiguration IsAutoExpand(bool autoExpand)
        {
            _autoExpand = autoExpand;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_autoExpand.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("AutoExpand", new EdmBooleanConstant(_autoExpand.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
