// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// A unique identifier for nested entities within a request.
    /// </summary>
    public partial class ContentIDConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private string _contentID;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ContentID";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="ContentIDConfiguration"/></returns>
        public ContentIDConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// A unique identifier for nested entities within a request.
        /// </summary>
        /// <param name="contentID">The value to set</param>
        /// <returns><see cref="ContentIDConfiguration"/></returns>
        public ContentIDConfiguration HasContentID(string contentID)
        {
            _contentID = contentID;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (!string.IsNullOrEmpty(_contentID))
            {
                properties.Add(new EdmPropertyConstructor("ContentID", new EdmStringConstant(_contentID)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
