// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// A unique identifier for nested entities within a request.
    /// </summary>
    public partial class ContentIDConfiguration : VocabularyTermConfiguration
    {
        private string _contentID;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ContentID";

        /// <summary>
        /// A unique identifier for nested entities within a request.
        /// </summary>
        /// <param name="contentID">The value to set</param>
        /// <returns><see cref="ContentIDConfiguration"/></returns>
        public ContentIDConfiguration HasContentID(string contentID)
        {
            _contentID = contentID;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmStringConstant(_contentID);
        }
    }
}
