// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Entity-ids follow OData URL conventions
    /// </summary>
    public partial class ConventionalIDsConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _conventionalIDs;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ConventionalIDs";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="ConventionalIDsConfiguration"/></returns>
        public ConventionalIDsConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Entity-ids follow OData URL conventions
        /// </summary>
        /// <param name="conventionalIDs">The value to set</param>
        /// <returns><see cref="ConventionalIDsConfiguration"/></returns>
        public ConventionalIDsConfiguration IsConventionalIDs(bool conventionalIDs)
        {
            _conventionalIDs = conventionalIDs;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_conventionalIDs.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("ConventionalIDs", new EdmBooleanConstant(_conventionalIDs.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
