// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Entity-ids follow OData URL conventions
    /// </summary>
    public partial class ConventionalIDsConfiguration : VocabularyTermConfiguration
    {
        private bool? _conventionalIDs;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ConventionalIDs";

        /// <summary>
        /// Entity-ids follow OData URL conventions
        /// </summary>
        /// <param name="conventionalIDs">The value to set</param>
        /// <returns><see cref="ConventionalIDsConfiguration"/></returns>
        public ConventionalIDsConfiguration IsConventionalIDs(bool conventionalIDs)
        {
            _conventionalIDs = conventionalIDs;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return _conventionalIDs.HasValue ? new EdmBooleanConstant(_conventionalIDs.Value) : null;
        }
    }
}
