// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Entity-ids are URLs that locate the identified entity
    /// </summary>
    public partial class DereferenceableIDsConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _dereferenceableIDs;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.DereferenceableIDs";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="DereferenceableIDsConfiguration"/></returns>
        public DereferenceableIDsConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Entity-ids are URLs that locate the identified entity
        /// </summary>
        /// <param name="dereferenceableIDs">The value to set</param>
        /// <returns><see cref="DereferenceableIDsConfiguration"/></returns>
        public DereferenceableIDsConfiguration IsDereferenceableIDs(bool dereferenceableIDs)
        {
            _dereferenceableIDs = dereferenceableIDs;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_dereferenceableIDs.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("DereferenceableIDs", new EdmBooleanConstant(_dereferenceableIDs.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
