// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Entity-ids are URLs that locate the identified entity
    /// </summary>
    public partial class DereferenceableIDsConfiguration : VocabularyTermConfiguration
    {
        private bool? _dereferenceableIDs;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.DereferenceableIDs";

        /// <summary>
        /// Entity-ids are URLs that locate the identified entity
        /// </summary>
        /// <param name="dereferenceableIDs">The value to set</param>
        /// <returns><see cref="DereferenceableIDsConfiguration"/></returns>
        public DereferenceableIDsConfiguration IsDereferenceableIDs(bool dereferenceableIDs)
        {
            _dereferenceableIDs = dereferenceableIDs;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return _dereferenceableIDs.HasValue ? new EdmBooleanConstant(_dereferenceableIDs) : null;
        }
    }
}
