// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Properties and terms annotated with this term are language-dependent
    /// </summary>
    public partial class IsLanguageDependentConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _isLanguageDependent;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.IsLanguageDependent";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="IsLanguageDependentConfiguration"/></returns>
        public IsLanguageDependentConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Properties and terms annotated with this term are language-dependent
        /// </summary>
        /// <param name="isLanguageDependent">The value to set</param>
        /// <returns><see cref="IsLanguageDependentConfiguration"/></returns>
        public IsLanguageDependentConfiguration IsIsLanguageDependent(bool isLanguageDependent)
        {
            _isLanguageDependent = isLanguageDependent;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_isLanguageDependent.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("IsLanguageDependent", new EdmBooleanConstant(_isLanguageDependent.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
