// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Properties and terms annotated with this term MUST contain a valid URL
    /// </summary>
    public partial class IsURLConfiguration : VocabularyTermConfiguration
    {
        private bool? _isURL;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.IsURL";

        /// <summary>
        /// Properties and terms annotated with this term MUST contain a valid URL
        /// </summary>
        /// <param name="isURL">The value to set</param>
        /// <returns><see cref="IsURLConfiguration"/></returns>
        public IsURLConfiguration IsIsURL(bool isURL)
        {
            _isURL = isURL;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmBooleanConstant(_isURL ?? true);
        }
    }
}
