// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Link to related information
    /// </summary>
    public partial class LinksConfiguration : VocabularyTermConfiguration
    {
        private readonly HashSet<LinkConfiguration> _links = new HashSet<LinkConfiguration>();

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.Links";

        /// <summary>
        /// Link to related information
        /// </summary>
        /// <param name="linksConfiguration">The configuration to set</param>
        /// <returns><see cref="LinksConfiguration"/></returns>
        public LinksConfiguration HasLinks(Func<LinkConfiguration, LinkConfiguration> linksConfiguration)
        {
            var instance = new LinkConfiguration();
            instance = linksConfiguration?.Invoke(instance);
            return HasLinks(instance);
        }

        /// <summary>
        /// Link to related information
        /// </summary>
        /// <param name="links">The value(s) to set</param>
        /// <returns><see cref="LinksConfiguration"/></returns>
        public LinksConfiguration HasLinks(params LinkConfiguration[] links)
        {
            _links.UnionWith(links);
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            if (!_links.Any())
            {
                return null;
            }

            var records = _links.Select(item => item.ToEdmExpression());
            return new EdmCollectionExpression(records);
        }
    }
}
