// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// A lengthy description of a model element
    /// </summary>
    public partial class LongDescriptionConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private string _longDescription;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.LongDescription";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="LongDescriptionConfiguration"/></returns>
        public LongDescriptionConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// A lengthy description of a model element
        /// </summary>
        /// <param name="longDescription">The value to set</param>
        /// <returns><see cref="LongDescriptionConfiguration"/></returns>
        public LongDescriptionConfiguration HasLongDescription(string longDescription)
        {
            _longDescription = longDescription;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (!string.IsNullOrEmpty(_longDescription))
            {
                properties.Add(new EdmPropertyConstructor("LongDescription", new EdmStringConstant(_longDescription)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
