// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// A lengthy description of a model element
    /// </summary>
    public partial class LongDescriptionConfiguration : VocabularyTermConfiguration
    {
        private string _longDescription;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.LongDescription";

        /// <summary>
        /// A lengthy description of a model element
        /// </summary>
        /// <param name="longDescription">The value to set</param>
        /// <returns><see cref="LongDescriptionConfiguration"/></returns>
        public LongDescriptionConfiguration HasLongDescription(string longDescription)
        {
            _longDescription = longDescription;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmStringConstant(_longDescription);
        }
    }
}
