// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Instance annotation for warning and info messages
    /// </summary>
    public partial class MessagesConfiguration : VocabularyTermConfiguration
    {
        private readonly HashSet<MessageTypeConfiguration> _messages = new HashSet<MessageTypeConfiguration>();

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.Messages";

        /// <summary>
        /// Instance annotation for warning and info messages
        /// </summary>
        /// <param name="messagesConfiguration">The configuration to set</param>
        /// <returns><see cref="MessagesConfiguration"/></returns>
        public MessagesConfiguration HasMessages(Func<MessageTypeConfiguration, MessageTypeConfiguration> messagesConfiguration)
        {
            var instance = new MessageTypeConfiguration();
            instance = messagesConfiguration?.Invoke(instance);
            return HasMessages(instance);
        }

        /// <summary>
        /// Instance annotation for warning and info messages
        /// </summary>
        /// <param name="messages">The value(s) to set</param>
        /// <returns><see cref="MessagesConfiguration"/></returns>
        public MessagesConfiguration HasMessages(params MessageTypeConfiguration[] messages)
        {
            _messages.UnionWith(messages);
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            if (!_messages.Any())
            {
                return null;
            }

            var records = _messages.Select(item => item.ToEdmExpression());
            return new EdmCollectionExpression(records);
        }
    }
}
