// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// A space-separated list of supported versions of the OData Protocol. Note that 4.0 is implied by 4.01 and does not need to be separately listed.
    /// </summary>
    public partial class ODataVersionsConfiguration : VocabularyTermConfiguration
    {
        private string _oDataVersions;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ODataVersions";

        /// <summary>
        /// A space-separated list of supported versions of the OData Protocol. Note that 4.0 is implied by 4.01 and does not need to be separately listed.
        /// </summary>
        /// <param name="oDataVersions">The value to set</param>
        /// <returns><see cref="ODataVersionsConfiguration"/></returns>
        public ODataVersionsConfiguration HasODataVersions(string oDataVersions)
        {
            _oDataVersions = oDataVersions;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmStringConstant(_oDataVersions);
        }
    }
}
