// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Collection has a stable order. Ordered collections of primitive or complex types can be indexed by ordinal.
    /// </summary>
    public partial class OrderedConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private bool? _ordered;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.Ordered";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="OrderedConfiguration"/></returns>
        public OrderedConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Collection has a stable order. Ordered collections of primitive or complex types can be indexed by ordinal.
        /// </summary>
        /// <param name="ordered">The value to set</param>
        /// <returns><see cref="OrderedConfiguration"/></returns>
        public OrderedConfiguration IsOrdered(bool ordered)
        {
            _ordered = ordered;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_ordered.HasValue)
            {
                properties.Add(new EdmPropertyConstructor("Ordered", new EdmBooleanConstant(_ordered.Value)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
