// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Terms annotated with this term can only be applied to elements that have a type that is identical to or derived from the given type name
    /// </summary>
    public partial class RequiresTypeConfiguration : VocabularyTermConfiguration
    {
        private string _requiresType;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.RequiresType";

        /// <summary>
        /// Terms annotated with this term can only be applied to elements that have a type that is identical to or derived from the given type name
        /// </summary>
        /// <param name="requiresType">The value to set</param>
        /// <returns><see cref="RequiresTypeConfiguration"/></returns>
        public RequiresTypeConfiguration HasRequiresType(string requiresType)
        {
            _requiresType = requiresType;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmStringConstant(_requiresType);
        }
    }
}
