// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// This bound action or function is only available on model elements annotated with the ExplicitOperationBindings term.
    /// </summary>
    public partial class RequiresExplicitBindingConfiguration : VocabularyTermConfiguration
    {
        private bool? _requiresExplicitBinding;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.RequiresExplicitBinding";

        /// <summary>
        /// This bound action or function is only available on model elements annotated with the ExplicitOperationBindings term.
        /// </summary>
        /// <param name="requiresExplicitBinding">The value to set</param>
        /// <returns><see cref="RequiresExplicitBindingConfiguration"/></returns>
        public RequiresExplicitBindingConfiguration IsRequiresExplicitBinding(bool requiresExplicitBinding)
        {
            _requiresExplicitBinding = requiresExplicitBinding;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return _requiresExplicitBinding.HasValue ? new EdmBooleanConstant(_requiresExplicitBinding.Value) : null;
        }
    }
}
