// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Resource path for entity container child, can be relative to xml:base and the request URL
    /// </summary>
    public partial class ResourcePathConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private string _resourcePath;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ResourcePath";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="ResourcePathConfiguration"/></returns>
        public ResourcePathConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Resource path for entity container child, can be relative to xml:base and the request URL
        /// </summary>
        /// <param name="resourcePath">The value to set</param>
        /// <returns><see cref="ResourcePathConfiguration"/></returns>
        public ResourcePathConfiguration HasResourcePath(string resourcePath)
        {
            _resourcePath = resourcePath;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (!string.IsNullOrEmpty(_resourcePath))
            {
                properties.Add(new EdmPropertyConstructor("ResourcePath", new EdmStringConstant(_resourcePath)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
