// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// The annotated instance within a success payload is problematic
    /// </summary>
    public partial class ResourceExceptionConfiguration : VocabularyTermConfiguration
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private MessageTypeConfiguration _info;
        private string _retryLink;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.ResourceException";

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="ResourceExceptionConfiguration"/></returns>
        public ResourceExceptionConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// Information about the exception
        /// </summary>
        /// <param name="infoConfiguration">The configuration to set</param>
        /// <returns><see cref="ResourceExceptionConfiguration"/></returns>
        public ResourceExceptionConfiguration Hasinfo(Func<MessageTypeConfiguration, MessageTypeConfiguration> infoConfiguration)
        {
            var instance = _info ?? new MessageTypeConfiguration();
            instance = infoConfiguration?.Invoke(instance);
            return Hasinfo(instance);
        }

        /// <summary>
        /// Information about the exception
        /// </summary>
        /// <param name="info">The value to set</param>
        /// <returns><see cref="ResourceExceptionConfiguration"/></returns>
        public ResourceExceptionConfiguration Hasinfo(MessageTypeConfiguration info)
        {
            _info = info;
            return this;
        }

        /// <summary>
        /// A GET request to this URL retries retrieving the problematic instance
        /// </summary>
        /// <param name="retryLink">The value to set</param>
        /// <returns><see cref="ResourceExceptionConfiguration"/></returns>
        public ResourceExceptionConfiguration HasretryLink(string retryLink)
        {
            _retryLink = retryLink;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (_info != null)
            {
                properties.Add(new EdmPropertyConstructor("info", _info.ToEdmExpression()));
            }

            if (!string.IsNullOrEmpty(_retryLink))
            {
                properties.Add(new EdmPropertyConstructor("retryLink", new EdmStringConstant(_retryLink)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
