// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Org.OData.Core.V1.RevisionType
    /// </summary>
    public partial class RevisionTypeConfiguration : IRecord
    {
        private readonly Dictionary<string, object> _dynamicProperties = new Dictionary<string, object>();
        private string _version;
        private RevisionKind? _kind;
        private string _description;

        /// <summary>
        /// Creates a new instance of <see cref="RevisionTypeConfiguration"/>
        /// </summary>
        public RevisionTypeConfiguration()
        {
        }

        /// <summary>
        /// Dynamic properties.
        /// </summary>
        /// <param name="name">The name to set</param>
        /// <param name="value">The value to set</param>
        /// <returns><see cref="RevisionTypeConfiguration"/></returns>
        public RevisionTypeConfiguration HasDynamicProperty(string name, object value)
        {
            _dynamicProperties[name] = value;
            return this;
        }

        /// <summary>
        /// The schema version with which this revision was first published
        /// </summary>
        /// <param name="version">The value to set</param>
        /// <returns><see cref="RevisionTypeConfiguration"/></returns>
        public RevisionTypeConfiguration HasVersion(string version)
        {
            _version = version;
            return this;
        }

        /// <summary>
        /// The kind of revision
        /// </summary>
        /// <param name="kind">The value to set</param>
        /// <returns><see cref="RevisionTypeConfiguration"/></returns>
        public RevisionTypeConfiguration HasKind(RevisionKind kind)
        {
            _kind = kind;
            return this;
        }

        /// <summary>
        /// Text describing the reason for the revision
        /// </summary>
        /// <param name="description">The value to set</param>
        /// <returns><see cref="RevisionTypeConfiguration"/></returns>
        public RevisionTypeConfiguration HasDescription(string description)
        {
            _description = description;
            return this;
        }

        /// <inheritdoc/>
        public IEdmExpression ToEdmExpression()
        {
            var properties = new List<IEdmPropertyConstructor>();

            if (!string.IsNullOrEmpty(_version))
            {
                properties.Add(new EdmPropertyConstructor("Version", new EdmStringConstant(_version)));
            }

            if (_kind.HasValue)
            {
                var enumType = new EdmEnumType("Org.OData.Core.V1", "RevisionKind", false);
                var enumMember = new EdmEnumMember(enumType, _kind.ToString(), new EdmEnumMemberValue((long)_kind.Value));
                properties.Add(new EdmPropertyConstructor("Kind", new EdmEnumMemberExpression(enumMember)));
            }

            if (!string.IsNullOrEmpty(_description))
            {
                properties.Add(new EdmPropertyConstructor("Description", new EdmStringConstant(_description)));
            }

            properties.AddRange(_dynamicProperties.ToEdmProperties());

            if (!properties.Any())
            {
                return null;
            }

            return new EdmRecordExpression(properties);
        }
    }
}
