// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Org.OData.Core.V1.RevisionKind
    /// </summary>
    public enum RevisionKind
    {
        /// <summary>
        /// Model element was added
        /// </summary>
        Added,

        /// <summary>
        /// Model element was modified
        /// </summary>
        Modified,

        /// <summary>
        /// Model element was deprecated
        /// </summary>
        Deprecated,
    }
}
