// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License.  See License.txt in the project root for license information.
// This is an auto generated file. Please run the template to modify it.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.OData.Edm;
using Microsoft.OData.Edm.Vocabularies;

namespace Microsoft.OData.ModelBuilder.Core.V1
{
    /// <summary>
    /// Service-defined value representing the version of the schema. Services MAY use semantic versioning, but clients MUST NOT assume this is the case.
    /// </summary>
    public partial class SchemaVersionConfiguration : VocabularyTermConfiguration
    {
        private string _schemaVersion;

        /// <inheritdoc/>
        public override string TermName => "Org.OData.Core.V1.SchemaVersion";

        /// <summary>
        /// Service-defined value representing the version of the schema. Services MAY use semantic versioning, but clients MUST NOT assume this is the case.
        /// </summary>
        /// <param name="schemaVersion">The value to set</param>
        /// <returns><see cref="SchemaVersionConfiguration"/></returns>
        public SchemaVersionConfiguration HasSchemaVersion(string schemaVersion)
        {
            _schemaVersion = schemaVersion;
            return this;
        }

        /// <inheritdoc/>
        public override IEdmExpression ToEdmExpression()
        {
            return new EdmStringConstant(_schemaVersion);
        }
    }
}
